# .github/workflows/deploy.yml
name: Deploy wingsview (build-in-place)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout isn't required for SSH-only deploys, but it's harmless.
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Deploy over SSH (server-side build)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -euo pipefail

            APP_DIR="/srv/www/wingsview"
            APP_NAME="wingsview"

            echo "→ cd ${APP_DIR}"
            cd "${APP_DIR}"

            echo "→ Reset working tree to origin/main (no local edits allowed)"
            git fetch origin
            git reset --hard origin/main

            echo "→ Install deps (include dev for TypeScript)"
            export NPM_CONFIG_PRODUCTION=false
            npm ci

            echo "→ Build (Next standalone)"
            npm run build

            echo "→ Sanity: standalone entry must exist"
            test -f ".next/standalone/server.js" || { echo "ERROR: .next/standalone/server.js not found. Is output: 'standalone' set?"; exit 1; }

            echo "→ Reload only ${APP_NAME}"
            pm2 reload "${APP_NAME}" || pm2 start ".next/standalone/server.js" --name "${APP_NAME}"
            pm2 save

            echo "✓ Deploy complete"
