# .github/workflows/deploy.yml
name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            echo "→ Navigating to app directory"
            cd /srv/www/wingsview

            echo "→ Git status before pull"
            git status

            echo "→ Pulling latest changes"
            git pull origin main

            echo "→ Installing dependencies"
            npm install --production=true

            echo "→ Building the app"
            npm run build

            echo "→ Restarting process manager (pm2)"
            pm2 restart all
            pm2 save